[opener]
edit = [
    { run = 'nvim %s', block = true, for = "unix" },
]

extract = [
    { run = '7z x %s', desc = "Extract", block = true, for = "unix" },
]

[open]
rules = [
    { mime = "text/*", use = [ "edit" ] },
    
    # "url" is the correct Yazi key for extension matching
    { url = "*.zip", use = [ "extract" ] },
    { url = "*.7z", use = [ "extract" ] },
    { url = "*.rar", use = [ "extract" ] },
]

